document.querySelectorAll('a[href^="#"]').forEach(link=>{link.addEventListener('click',e=>{const target=document.querySelector(link.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}})});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const profileCaption=document.querySelector('.art-caption');
if(profileCaption){const label=profileCaption.querySelector('small');const name=profileCaption.querySelector('strong');if(label)label.textContent='GRAPHIC DESIGNER';if(name)name.textContent='ASHIKE RASUL MAHADI';}
const artTag=document.querySelector('.art-tag');
if(artTag)artTag.innerHTML='<strong>→ IDEA<br>→ DESIGN<br>→ IMPACT</strong>';
const experienceCards=document.querySelectorAll('.experience-card');
experienceCards.forEach(card=>{const button=card.querySelector('.role-action');const setOpen=open=>{card.classList.toggle('open',open);if(button){button.setAttribute('aria-expanded',open?'true':'false');button.querySelector('span').textContent=open?'↗':'＋';}};if(button){button.addEventListener('click',e=>{e.stopPropagation();setOpen(!card.classList.contains('open'));});}card.addEventListener('click',e=>{if(e.target.closest('button,a')) return;setOpen(!card.classList.contains('open'));});});
if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.08;const y=(e.clientY-r.top-r.height/2)*.08;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}
const experienceStyle=document.createElement('style');
experienceStyle.textContent=`
.experience-section{background:#f7f4ed;padding-top:125px;padding-bottom:125px}.experience-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;align-items:start}.experience-card{background:#fff;border:1px solid #ddd6ca;border-radius:18px;padding:28px;min-height:238px;display:flex;flex-direction:column;justify-content:space-between;box-shadow:0 12px 35px rgba(23,24,23,.045);transition:transform .35s cubic-bezier(.2,.8,.2,1),box-shadow .35s ease,border-color .3s ease,background .3s ease;position:relative;z-index:1;cursor:pointer}.experience-card:hover{transform:translateY(-7px);box-shadow:0 24px 55px rgba(23,24,23,.11);border-color:#b99a70}.experience-card.open{border-color:#a57a43;box-shadow:0 30px 75px rgba(23,24,23,.15);transform:translateY(-10px) scale(1.012);z-index:10;background:#fffefa}.experience-card.open:not(:last-child){grid-column:span 2}.experience-card:nth-child(5){grid-column:1/-1}.experience-card:nth-child(5).open{grid-column:1/-1}.role-top{display:flex;justify-content:space-between;align-items:flex-start;gap:20px}.role-top time{display:block;font-size:9px;letter-spacing:1.5px;font-weight:700;color:#a57a43;margin-bottom:11px}.role-top h3{font-family:'Space Grotesk';font-size:24px;line-height:1.08;letter-spacing:-.8px}.role-top p{font-size:11px;color:#777;margin-top:7px}.role-action{border:1px solid #cfc7ba;background:#f7f4ed;color:#252825;border-radius:100px;padding:10px 13px;font:700 10px 'DM Sans',sans-serif;white-space:nowrap;cursor:pointer;transition:.25s;flex-shrink:0}.role-action:hover,.experience-card.open .role-action{background:#17201e;color:#fff;border-color:#17201e}.role-action span{margin-left:6px}.role-details{display:grid;grid-template-rows:0fr;opacity:0;transition:grid-template-rows .45s cubic-bezier(.2,.8,.2,1),opacity .25s ease,margin-top .35s ease;margin-top:0}.role-details>*{overflow:hidden}.experience-card.open .role-details{grid-template-rows:1fr;opacity:1;margin-top:24px}.role-details p{font-size:12px;color:#5f605d;margin-bottom:12px;max-width:820px}.role-details ul{padding-left:17px;color:#70716d;font-size:11px;line-height:1.85;max-width:900px}.experience-card:after{content:'CLICK TO EXPAND';position:absolute;right:28px;bottom:18px;font-size:7px;letter-spacing:1.5px;color:#aaa;opacity:.8;transition:.2s}.experience-card.open:after{content:'CLICK TO COLLAPSE';color:#a57a43}.experience-card.open .role-details:before{content:'RESPONSIBILITIES & SCOPE';display:block;font-size:8px;letter-spacing:1.6px;font-weight:700;color:#a57a43;margin-bottom:10px}
.art-tag{width:142px;height:142px;left:-42px;right:auto;bottom:90px;border-radius:50%;padding:20px;text-align:center;display:flex;align-items:center;justify-content:center;font-size:8px;letter-spacing:1px;line-height:1.25}.art-tag strong{font-family:Arial,Helvetica,sans-serif;font-size:9px;line-height:1.8;letter-spacing:1px;font-weight:700;color:#fff;white-space:nowrap}.art-tag span{display:none}
@media(max-width:1050px){.art-tag{left:-25px;right:auto}}@media(max-width:900px){.experience-grid{grid-template-columns:1fr}.experience-card.open,.experience-card.open:not(:last-child),.experience-card:nth-child(5),.experience-card:nth-child(5).open{grid-column:auto}.experience-card.open{transform:translateY(-5px) scale(1.005)}.art-tag{left:-18px;right:auto;bottom:65px}}@media(max-width:650px){.experience-section{padding-top:80px;padding-bottom:80px}.experience-card{padding:21px;border-radius:14px;min-height:210px}.role-top{display:block}.role-action{margin-top:18px}.role-top h3{font-size:20px}.experience-card:after{right:21px;bottom:14px;font-size:6px}.art-tag{left:-7px;right:auto;bottom:48px;width:104px;height:104px;padding:12px;font-size:7px;line-height:1.15;letter-spacing:.8px}.art-tag strong{font-size:7px;line-height:1.65;letter-spacing:.7px}}
`;
document.head.appendChild(experienceStyle);

const videoCard=document.querySelector('#work .case:nth-child(8)');
if(videoCard){
 const placeholder=videoCard.querySelector('.placeholder');
 if(placeholder){
  placeholder.classList.add('portfolio-video');
  placeholder.innerHTML='<video src="assets/Bashundhara%20Night%20Delivery%20A-Z.mp4" muted loop playsinline preload="metadata"></video><div class="portfolio-video-label"><small>08 · VIDEO / MOTION</small><span>Bashundhara Night Delivery</span></div>';
  const v=placeholder.querySelector('video');
  if(v){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)v.play().catch(()=>{});else v.pause()}),{threshold:.35});io.observe(videoCard);}
 }
}
